### ISSUE TITLE
使用说明过于简略

### ISSUE THREAD

**Issue by wangke8023** [lyirs/rasa_CN#1]
大佬，项目启动的流程可以详细一点吗，比如最小路径启动到使用的具体步骤，谢谢大佬，python不是主语言，您的这个使用文档看的有点懵逼呀

**Comment by lyirs** [comment]
这个是基于RASA项目的_(:з」∠)_
https://github.com/RasaHQ/rasa

之后我加个详细的文档吧_(:з」∠)_
