### ISSUE TITLE
pipeline中是否缺少文件？

### ISSUE THREAD

**Issue by bobolele** [lyirs/rasa_CN#4]
训练的时候提示这个错误：
OSError: pipline/bert-base-chinese is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
是否是这个预训练模型没有上传？

**Comment by lyirs** [comment]
对的，太大了就没传
https://huggingface.co/bert-base-chinese
在这里下载
主要是
_config.json
pytorch_model.bin
tf_model.h5
tokenizer_config.json
vocab.txt_
五个文件
放到pipeline/bert-base-chinese中就可以啦
